#!/bin/bash

alias ls='ls --color -FA'

alias c='clear'
alias e='emacs -nw'
alias g='grep'
alias p='perl'

alias say='espeak'

alias cde='cd $E'

alias rebash='source ~/.bashrc'

alias java='/usr/bin/java "$@" 2> >(grep -v "^Picked up.*OPTION" >&2)'
