#!/bin/bash

function record_command_start_time() {
    if [[ $PROMPT_LOCAL_READY == "TRUE" ]]; then
        export PROMPT_LOCAL_START_TIME=$(date +%s%N | cut -b1-13)
        export PROMPT_LOCAL_READY="FALSE"
    fi
}
function record_command_stop_time() {
    export PROMPT_LOCAL_STOP_TIME=$(date +%s%N | cut -b1-13)
}
function execute_trap(){
    record_command_start_time;
    echo -ne '\033[0m'
}

# Colored prompt
function proml {
    if [[ $FIRST_PROM == "" ]]; then
        echo "Hello!"
	export PROMPT_LOCAL_READY="TRUE";
	record_command_start_time;
        export FIRST_PROM="nope";
    fi

    record_command_stop_time;
    export PROMPT_LOCAL_READY="TRUE"

    local          RED="\[\033[0;31m\]"
    local    LIGHT_RED="\[\033[1;31m\]"
    local       YELLOW="\[\033[0;33m\]"
    local LIGHT_YELLOW="\[\033[1;33m\]"
    local        GREEN="\[\033[0;32m\]"
    local  LIGHT_GREEN="\[\033[1;32m\]"
    local         BLUE="\[\033[0;34m\]"
    local   LIGHT_BLUE="\[\033[1;34m\]"
    local       PURPLE="\[\033[0;35m\]"
    local LIGHT_PURPLE="\[\033[1;35m\]"
    local         CYAN="\[\033[0;36m\]"
    local   LIGHT_CYAN="\[\033[1;36m\]"
    local         GRAY="\[\033[0;37m\]"
    local    DARK_GRAY="\[\033[1;30m\]"
    local        WHITE="\[\033[1;37m\]"
    local        PLAIN="\[\033[0m\]"
    local         BOLD="\[\033[1;30m\]"

    #colors of form where last number is the color # from ~juckele/bin/colors
    local       ORANGE="\[\033[38;5;214m\]"
    local         PINK="\[\033[38;5;217m\]"

    case $TERM in
        xterm*)
            TITLEBAR='[0;32m\t\033]0;\u \h:\W\007\]'
            ;;
        *)
            TITLEBAR=""
            ;;
    esac

    # command time computation
    local delta_ms="$((PROMPT_LOCAL_STOP_TIME - $PROMPT_LOCAL_START_TIME))"
    local delta_seconds="$(($delta_ms / 1000))"
    local delta_centiseconds="$((delta_ms % 1000 / 100))"
    local delta_centiseconds=$(printf "%0*d" 2 $delta_centiseconds)
    local pretty_delta="$(date -d @$((18000 + $delta_seconds)) +%T)"
    #echo $delta_ms
    #echo $delta_seconds
    #echo $delta_centiseconds
    #echo $pretty_delta
    
    # Git Branch
    local git_branch=$(git branch 2>/dev/null | grep \* | sed 's/* //')
    local git_branch=$(echo $git_branch | sed 's/juckele\///')
    
    # Host color, darker on unusual hosts
    local host=$(echo -e "$HOSTNAME" | sed 's/\..*//');

    if [[ $USER == "juckele" ]]; then
        local user_name="我"
    else
        local user_name="$USER"
    fi

    if [[ $host == "juckele-mbp" ]]; then
        local host_color="$DARK_GRAY"
	local host_name="mbp"
    else
        local host_color="$RED"
	local host_name="$host"
    fi

    local time_color="$GREEN"
    local user_color="$ORANGE"
    local git_color="$BLUE"
    local path_color="$PURPLE"
    local input_color="$LIGHT_PURPLE"
    local operator_color="$YELLOW"
    local operator_color2="$LIGHT_YELLOW"
    local operator_color3="$LIGHT_RED"

# $user_color\u
    PS1="$PINK$pretty_delta$time_color\t $user_color$user_name$host_color$host_name $git_color$git_branch$path_color\w $operator_color输入 $input_color"
    PS2='$operator_color2什么$PLAIN '
    PS4='$operator_color3输入$PLAIN '
}

## Color revert
# Experiment with color trapping...
trap "execute_trap" DEBUG

# actually set the prompt_command
export PROMPT_COMMAND=proml

